version: "3.9"

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    volumes:
      - "./app/build/classes/java/main:/app/classes"
      - "./app/build/resources/main:/app/resources"
    entrypoint: ["java", "-Dspring.profiles.active=docker", "-cp", "libs/*:classes:resources", "com.example.DockerComposeApplication"]
    #entrypoint: ["/bin/sh", "-c", "while true; do sleep 2; date; done"]
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27027:27017"
