FROM gradle:6.7.1-jdk8-hotspot AS cache
RUN mkdir -p /home/gradle/cache_home
ENV GRADLE_USER_HOME /home/gradle/cache_home
COPY settings.gradle /home/gradle/java-code/
COPY app/build.gradle /home/gradle/java-code/app/
COPY agent/build.gradle /home/gradle/java-code/agent/
WORKDIR /home/gradle/java-code/app
RUN gradle copyDependencies \
&& echo $(ls build/dependencies)

FROM adoptopenjdk:8-jdk-hotspot
#处理时区，占用1.78m
ENV TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive
RUN apt update \
    && apt install -y tzdata \
    && ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/*
EXPOSE 8080
WORKDIR /app
COPY --from=cache /home/gradle/java-code/app/build/dependencies libs
COPY agent/lib/HotSwapAgent.jar /usr/local/hotswap/

ENTRYPOINT ["java", "-cp", "libs/*:classes:resources", "com.example.DockerComposeApplication"]