FROM gradle:6.7.1-jdk8-hotspot AS cache
RUN mkdir -p /home/gradle/cache_home
ENV GRADLE_USER_HOME /home/gradle/cache_home
COPY settings.gradle /home/gradle/java-code/
COPY app/build.gradle /home/gradle/java-code/app/
COPY agent/build.gradle /home/gradle/java-code/agent/
WORKDIR /home/gradle/java-code/app
RUN gradle copyDependencies \
&& echo $(ls build/dependencies)

FROM adoptopenjdk:8-jdk-hotspot
EXPOSE 8080
WORKDIR /app
COPY --from=cache /home/gradle/java-code/app/build/dependencies libs
COPY agent/lib/HotSwapAgent.jar /usr/local/hotswap/

#处理时区
ENV TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive
RUN ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone

ENTRYPOINT ["java", "-cp", "libs/*:classes:resources", "com.example.DockerComposeApplication"]