version: "3.9"

services:
  nginx:
    image: nginx:stable
    ports:
      - "8070:8080"
    volumes:
      - "./docker/nginx.conf:/etc/nginx/nginx.conf"

  web:
    build: .
    ports:
      - "8081:8080"
    entrypoint: ["java", "-Dspring.profiles.active=docker", "-jar", "app.jar"]
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27027:27017"
